---
sidebar: sidebar 
permalink: backup/saphana-backup-anf-overview.html 
keywords: overview, introduction, tr-4905, 4905, tr4905, snapcenter service, anf, azure netapp files 
summary: 本技术报告介绍了使用 NetApp SnapCenter 服务和 Azure NetApp Files 保护 SAP HANA 数据的最佳实践。其中包括 SnapCenter 服务概念，配置建议和操作工作流，包括备份，还原和恢复操作。 
---
= TR-4905 ：《使用 SnapCenter 服务在 Azure NetApp Files 上备份和恢复 SAP HANA 》
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


NetApp 公司 Nil Bauser

本技术报告介绍了使用 NetApp SnapCenter 服务和 Azure NetApp Files 保护 SAP HANA 数据的最佳实践。其中包括 SnapCenter 服务概念，配置建议和操作工作流，包括备份，还原和恢复操作。

如今，企业需要为其 SAP 应用程序提供持续，无中断的可用性。面对不断增加的数据量以及系统备份等日常维护任务的需求，他们希望性能水平保持一致。执行 SAP 数据库备份是一项关键任务，可能会对生产 SAP 系统产生显著的性能影响。

备份窗口在缩减，而要备份的数据量在增加。因此，很难找到对业务流程影响最小的备份时间。恢复和恢复 SAP 系统所需的时间值得关注，因为 SAP 生产系统和非生产系统的停机时间必须尽可能地减少，以减少数据丢失和业务成本。

以下几点总结了 SAP 备份和恢复面临的挑战：

* * 性能对生产 SAP 系统的影响。 * 通常，由于数据库服务器，存储系统和存储网络上的负载过重，基于副本的传统备份会显著降低生产 SAP 系统的性能。
* * 正在缩减备份时间。 * 只有在 SAP 系统上正在进行的对话或批处理活动很少时，才能进行常规备份。当 SAP 系统 24 小时运行时，备份计划变得更加困难。
* * 数据快速增长。 * 数据快速增长和备份时间不断缩短需要对备份基础架构进行持续投资。换言之，您必须购买额外的备份磁盘空间和更快的备份网络。您还必须支付这些备份资产的持续存储和管理费用。增量备份或差异备份可以解决这些问题，但这种安排会导致还原过程非常缓慢，繁琐且复杂，难以验证。此类系统通常会以业务无法接受的方式增加恢复时间目标（ RTO ）和恢复点目标（ RPO ）时间。
* * 停机成本不断增加。 * SAP 系统的计划外停机通常会影响业务财务。在任何计划外停机中，很大一部分是由于需要还原和恢复 SAP 系统而造成的。因此，所需的 RTO 决定了备份和恢复架构的设计。
* * SAP 升级项目的备份和恢复时间。 * SAP 升级项目计划至少包括 SAP 数据库的三个备份。这些备份可显著缩短升级过程所需的时间。决定是否继续通常取决于从先前创建的备份还原和恢复数据库所需的时间。快速还原可以提供更多时间来解决升级期间可能发生的问题，而不仅仅是将系统还原到先前的状态。


link:saphana-backup-anf-the-netapp-solution.html["下一步： NetApp 解决方案。"]
