---
sidebar: sidebar 
permalink: backup/saphana-br-scs-where-to-find-additional-information.html 
keywords:  
summary:  
---
= 从何处查找追加信息和版本历史记录
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:saphana-br-scs-advanced-configuration-and-tuning.html["先前版本：高级配置和调整。"]

要了解有关本文档中所述信息的更多信息，请查看以下文档和 / 或网站：

* SnapCenter 资源页面
+
https://www.netapp.com/us/documentation/snapcenter-software.aspx["https://www.netapp.com/us/documentation/snapcenter-software.aspx"^]

* SnapCenter 软件文档
+
https://docs.netapp.com/us-en/snapcenter/index.html["https://docs.netapp.com/us-en/snapcenter/index.html"^]

* TR-4667 ：使用 SnapCenter 自动执行 SAP 系统副本
+
https://www.netapp.com/pdf.html?item=/media/17111-tr4667pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17111-tr4667pdf.pdf"^]

* TR-4719 ：《使用 SnapCenter 进行 SAP HANA 系统复制，备份和恢复》
+
https://www.netapp.com/pdf.html?item=/media/17030-tr4719pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17030-tr4719pdf.pdf"^]

* TR-4018 ：《将 NetApp ONTAP 系统与 SAP Landscape Management 集成》
+
https://www.netapp.com/pdf.html?item=/media/17195-tr4018pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17195-tr4018pdf.pdf"^]

* TR-4646 ：《使用存储复制实现 SAP HANA 灾难恢复》
+
https://www.netapp.com/pdf.html?item=/media/8584-tr4646pdf.pdf["https://www.netapp.com/pdf.html?item=/media/8584-tr4646pdf.pdf"^]





=== 版本历史记录

|===
| version | Date | 文档版本历史记录 


| 版本 1.0 | 2017年7月  a| 
* 初始版本。




| 版本 1.1 | 2017 年 9 月  a| 
* 添加了 " 高级配置和调整 " 一节。
* 轻微更正。




| 版本 2.0 | 2018年3月  a| 
* 更新了 SnapCenter 4.0 ：新的数据卷资源改进了单文件 SnapRestore 操作




| 版本 3.0 | 2020年1月  a| 
* 添加了 SnapCenter 概念和最佳实践一节。
* 更新了 SnapCenter 4.3 ：自动发现自动还原和恢复支持 HANA MDC 多租户单租户还原操作




| 版本 3.1 | 2020 年 7 月  a| 
* 次要更新和更正： SnapCenter 4.3.1 支持 NFSv4 在 IBM Power 上为 Linux 配置 SSL 通信中央插件部署




| 版本 3.2 | 2020年11月  a| 
* 已为 HANA 2.0 SPS5 添加所需的数据库用户权限。




| 版本 3.3 | 2021 年 5 月  a| 
* 已更新 SSL hdbsql" 配置 " 部分。
* 增加了对 Linux LVM 的支持。




| 版本 3.4 | 2021年8月  a| 
* 已添加禁用自动发现配置问题描述 。




| 版本 3.5 | 2022 年 2 月  a| 
* 对 SnapCenter 4.6 进行了少量更新，并支持对启用了 HANA 系统复制的 HANA 系统进行自动发现。


|===