---
sidebar: sidebar 
permalink: bp/hana-asa-fc-software-install.html 
keywords: software, installation, 
summary: 本节介绍在单主机和多主机系统上安装 SAP HANA 所需的准备工作。 
---
= SAP HANA 软件安装
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
本节介绍在单主机和多主机系统上安装 SAP HANA 所需的准备工作。



== 在单主机系统上安装

SAP HANA 软件安装不需要为单主机系统做任何其他准备。



== 在多主机系统上安装

开始安装之前，请创建一个 `global.ini` 文件，以便在安装过程中使用 SAP 存储连接器。在安装过程中， SAP 存储连接器会在工作主机上挂载所需的文件系统。`global.ini` 文件必须位于可从所有主机访问的文件系统中，例如， ` /ha/shared` 文件系统。

在多主机系统上安装 SAP HANA 软件之前，必须完成以下步骤：

. 将以下数据 LUN 和日志 LUN 的挂载选项添加到 `global.ini` 文件中：
+
** `relatime` 和 `inode64` 用于数据和日志文件系统


. 添加数据分区和日志分区的 WWID 。WWID 必须与 ` /etc/multipath.conf` 文件中配置的别名匹配。
+
以下示例显示了一个 2+1 多主机设置，其中 SID 为 FC5 。

+
....
sapcc-hana-tst-03:/hana/shared # cat global.ini
[communication]
listeninterface = .global
[persistence]
basepath_datavolumes = /hana/data/FC5
basepath_logvolumes = /hana/log/FC5
[storage]
ha_provider = hdb_ha.fcClientLVM
partition_*_*__prtype = 5
partition_*_data__mountOptions = -o relatime,inode64
partition_*_log__mountOptions = -o relatime,inode64
partition_1_data__lvmname = FC5_data_mnt00001-vol
partition_1_log__lvmname = FC5_log_mnt00001-vol
partition_2_data__lvmname = FC5_data_mnt00002-vol
partition_2_log__lvmname = FC5_log_mnt00002-vol
sapcc-hana-tst-03:/hana/shared #
....


使用 SAP hdblcm 安装工具，在其中一个工作主机上运行以下命令开始安装。使用 `addhosts`选项添加第二个工作空间(sapcc-hana TST-06)和备用主机(sapcc-hana TST-07)。

+


NOTE: 命令行界面选项中包含了用于存储准备文件的 `storage_cfg`目录 `global.ini`(`--storage_cfg=/hana/shared`)。

+


NOTE: 根据所使用的操作系统版本，可能需要先安装 Python 2.7 ，然后再安装 SAP HANA 数据库。

+

....
./hdblcm --action=install --addhosts=sapcc-hana-tst-06:role=worker:storage_partition=2,sapcc-hana-tst-07:role=standby --storage_cfg=/hana/shared/

AP HANA Lifecycle Management - SAP HANA Database 2.00.073.00.1695288802
************************************************************************


Scanning software locations...
Detected components:
    SAP HANA AFL (incl.PAL,BFL,OFL) (2.00.073.0000.1695321500) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/HDB_AFL_LINUX_X86_64/packages
    SAP HANA Database (2.00.073.00.1695288802) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/HDB_SERVER_LINUX_X86_64/server
    SAP HANA Database Client (2.18.24.1695756995) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/HDB_CLIENT_LINUX_X86_64/SAP_HANA_CLIENT/client
    SAP HANA Studio (2.3.75.000000) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/HDB_STUDIO_LINUX_X86_64/studio
    SAP HANA Local Secure Store (2.11.0) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/HANA_LSS_24_LINUX_X86_64/packages
    SAP HANA XS Advanced Runtime (1.1.3.230717145654) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSA_RT_10_LINUX_X86_64/packages
    SAP HANA EML AFL (2.00.073.0000.1695321500) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/HDB_EML_AFL_10_LINUX_X86_64/packages
    SAP HANA EPM-MDS (2.00.073.0000.1695321500) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/SAP_HANA_EPM-MDS_10/packages
    Automated Predictive Library (4.203.2321.0.0) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/PAAPL4_H20_LINUX_X86_64/apl-4.203.2321.0-hana2sp03-linux_x64/installer/packages
    GUI for HALM for XSA (including product installer) Version 1 (1.015.0) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSA_CONTENT_10/XSACALMPIUI15_0.zip
    XSAC FILEPROCESSOR 1.0 (1.000.102) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSA_CONTENT_10/XSACFILEPROC00_102.zip
    SAP HANA tools for accessing catalog content, data preview, SQL console, etc. (2.015.230503) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSAC_HRTT_20/XSACHRTT15_230503.zip
    Develop and run portal services for customer applications on XSA (2.007.0) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSA_CONTENT_10/XSACPORTALSERV07_0.zip
    The SAP Web IDE for HANA 2.0 (4.007.0) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSAC_SAP_WEB_IDE_20/XSACSAPWEBIDE07_0.zip
    XS JOB SCHEDULER 1.0 (1.007.22) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSA_CONTENT_10/XSACSERVICES07_22.zip
    SAPUI5 FESV6 XSA 1 - SAPUI5 1.71 (1.071.52) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSA_CONTENT_10/XSACUI5FESV671_52.zip
    SAPUI5 FESV9 XSA 1 - SAPUI5 1.108 (1.108.5) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSA_CONTENT_10/XSACUI5FESV9108_5.zip
    SAPUI5 SERVICE BROKER XSA 1 - SAPUI5 Service Broker 1.0 (1.000.4) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSA_CONTENT_10/XSACUI5SB00_4.zip
    XSA Cockpit 1 (1.001.37) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSA_CONTENT_10/XSACXSACOCKPIT01_37.zip


SAP HANA Database version '2.00.073.00.1695288802' will be installed.

Select additional components for installation:

  Index | Components      | Description
  --------------------------------------------------------------------------------------------------
  1     | all             | All components
  2     | server          | No additional components
  3     | client          | Install SAP HANA Database Client version 2.18.24.1695756995
  4     | lss             | Install SAP HANA Local Secure Store version 2.11.0
  5     | studio          | Install SAP HANA Studio version 2.3.75.000000
  6     | xs              | Install SAP HANA XS Advanced Runtime version 1.1.3.230717145654
  7     | afl             | Install SAP HANA AFL (incl.PAL,BFL,OFL) version 2.00.073.0000.1695321500
  8     | eml             | Install SAP HANA EML AFL version 2.00.073.0000.1695321500
  9     | epmmds          | Install SAP HANA EPM-MDS version 2.00.073.0000.1695321500
  10    | sap_afl_sdk_apl | Install Automated Predictive Library version 4.203.2321.0.0

Enter comma-separated list of the selected indices [3,4]: 2,3

....
. 验证安装工具是否已在所有工作主机和备用主机上安装所有选定组件。

