---
sidebar: sidebar 
permalink: bp/hana-aff-fc-host-setup_multi.html 
keywords: multipathing, fcp, hba, configure 
summary: 在设置主机之前，必须从 NetApp 支持站点下载 NetApp SAN 主机实用程序，并将其安装在 HANA 服务器上。主机实用程序文档提供了有关根据所使用的 FCP HBA 而必须安装的其他软件的信息。 
---
= 多主机设置
:allow-uri-read: 




== 多主机设置

[role="lead"]
本章以 2+1 SAP HANA 多主机系统的设置为例进行描述。



== SAP HANA 多主机系统的 LUN 配置

在 SAP HANA 主机上，需要创建和挂载卷组和逻辑卷，如下表所示。

|===
| 逻辑卷（ LV ）或卷 | SAP HANA 主机上的挂载点 | 注意 


| LV：FC5_data_mnt00001-vol | /ha/data/FC5/mnt00001 | 使用存储连接器挂载 


| LV：FC5_log_mnt00001-vol | /ha/log/FC5/mnt00001 | 使用存储连接器挂载 


| LV：FC5_data_mnt00002-vol | /ha/data/FC5/mnt00002 | 使用存储连接器挂载 


| LV：FC5_log_mnt00002-vol | /ha/log/FC5/mnt00002 | 使用存储连接器挂载 


| 卷：FC5_shared | /has/ 共享 | 使用 NFS 和 /etc/fstab 条目挂载在所有主机上 
|===

NOTE: 通过所述配置， `/usr/sap/FC5`存储用户 FC5adm 的默认主目录的目录位于每个 HANA 主机的本地磁盘上。在基于磁盘的复制灾难恢复设置中， NetApp建议在 `FC5_shared`音量为 `/usr/sap/FC5`文件系统，以便每个数据库主机在中央存储上都有其所有的文件系统。



=== 创建 LVM 卷组和逻辑卷

. 将所有 LUN 初始化为物理卷。
+
....
pvcreate /dev/mapper/hana-FC5_data_mnt00001
pvcreate /dev/mapper/hana-FC5_data2_mnt00001
pvcreate /dev/mapper/hana-FC5_data_mnt00002
pvcreate /dev/mapper/hana-FC5_data2_mnt00002
pvcreate /dev/mapper/hana-FC5_log_mnt00001
pvcreate /dev/mapper/hana-FC5_log2_mnt00001
pvcreate /dev/mapper/hana-FC5_log_mnt00002
pvcreate /dev/mapper/hana-FC5_log2_mnt00002
....
. 为每个数据和日志分区创建卷组。
+
....
vgcreate FC5_data_mnt00001 /dev/mapper/hana-FC5_data_mnt00001 /dev/mapper/hana-FC5_data2_mnt00001
vgcreate FC5_data_mnt00002 /dev/mapper/hana-FC5_data_mnt00002 /dev/mapper/hana-FC5_data2_mnt00002
vgcreate FC5_log_mnt00001 /dev/mapper/hana-FC5_log_mnt00001 /dev/mapper/hana-FC5_log2_mnt00001
vgcreate FC5_log_mnt00002 /dev/mapper/hana-FC5_log_mnt00002 /dev/mapper/hana-FC5_log2_mnt00002
....
. 为每个数据和日志分区创建一个逻辑卷。使用的条带大小等于每个卷组使用的 LUN 数量（在此示例中为 2 个），数据条带大小为 256k ，日志条带大小为 64k 。SAP 仅支持每个卷组一个逻辑卷。
+
....
lvcreate --extents 100%FREE -i 2 -I 256k --name vol FC5_data_mnt00001
lvcreate --extents 100%FREE -i 2 -I 256k --name vol FC5_data_mnt00002
lvcreate --extents 100%FREE -i 2 -I 64k --name vol FC5_log_mnt00002
lvcreate --extents 100%FREE -i 2 -I 64k --name vol FC5_log_mnt00001
....
. 扫描所有其他主机上的物理卷，卷组和卷组。


....
modprobe dm_mod
pvscan
vgscan
lvscan
....

NOTE: 如果这些命令未找到卷，则需要重新启动。

要挂载逻辑卷，必须激活逻辑卷。要激活卷，请运行以下命令：

....
vgchange -a y
....


=== 创建文件系统

在所有数据和日志逻辑卷上创建 XFS 文件系统。

....
mkfs.xfs FC5_data_mnt00001-vol
mkfs.xfs FC5_data_mnt00002-vol
mkfs.xfs FC5_log_mnt00001-vol
mkfs.xfs FC5_log_mnt00002-vol
....


=== 创建挂载点

创建所需的挂载点目录，并在所有工作主机和备用主机上设置权限：

....
sapcc-hana-tst:/ # mkdir -p /hana/data/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/log/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/data/FC5/mnt00002
sapcc-hana-tst:/ # mkdir -p /hana/log/FC5/mnt00002
sapcc-hana-tst:/ # mkdir -p /hana/shared
sapcc-hana-tst:/ # chmod –R 777 /hana/log/FC5
sapcc-hana-tst:/ # chmod –R 777 /hana/data/FC5
sapcc-hana-tst:/ # chmod 777 /hana/shared
....


=== 挂载文件系统

要安装 `/hana/shared`文件系统在系统启动时使用 `/etc/fstab`配置文件，添加 `/hana/shared`文件系统 `/etc/fstab`每个主机的配置文件。

....
sapcc-hana-tst:/ # cat /etc/fstab
<storage-ip>:/hana_shared /hana/shared nfs rw,vers=3,hard,timeo=600, intr,noatime,nolock 0 0
....

NOTE: 所有数据和日志文件系统均通过 SAP HANA 存储连接器挂载。

要挂载文件系统，请在每个主机上运行 `mount – a` 命令。
