---
sidebar: sidebar 
permalink: bp/hana-asa-fc-storage-controller-setup_single_host.html 
keywords: storage efficiency, netapp volume encryption, quality of service, qos, fabricpool, Disk shelf, sas, fcp port sets, linux lvm, 
summary: 本节介绍 NetApp 存储系统的配置。您必须根据相应的 Data ONTAP 设置和配置指南完成主安装和设置。 
---
= 存储控制器设置 - 单主机
:allow-uri-read: 




== 存储控制器设置 - 单主机

[role="lead"]
本节介绍针对 SAP HANA 单主机系统的 NetApp 存储系统配置



== SAP HANA 单主机系统的 LUN 配置

Linux LVM 用于提高性能并解决 LUN 大小限制。在 SAP HANA 主机上，需要创建和挂载卷组和逻辑卷，如下表所示。

|===
| 逻辑卷 /LUN | SAP HANA 主机上的挂载点 | 注意 


| LV：FC5_data_mnt0000-vol | /ha/data/FC5/mnt00001 | 已使用 /etc/fstab 条目挂载 


| LV：FC5_log_mnt00001-vol | /ha/log/FC5/mnt00001 | 已使用 /etc/fstab 条目挂载 


| LUN：FC5_共享 | /has/shared/FC5 | 已使用 /etc/fstab 条目挂载 
|===

NOTE: 通过所述配置，  `/usr/sap/FC5`存储用户 FC5adm 默认主目录的目录位于本地磁盘上。在基于磁盘的复制灾难恢复设置中，NetApp 建议为 `/usr/sap/FC5`目录，以便所有文件系统都位于中央存储上。



== 创建 LUN 并将 LUN 映射到启动程序组

您可以使用NetApp ONTAP系统管理器创建存储卷和LUN、并将其映射到服务器的igrou和ONTAP命令行界面。本指南介绍命令行界面的用法。


NOTE: `sanlun` 工具是 NetApp Host Utilities 的一部分，必须安装在每个 SAP HANA 主机上。有关详细信息，请参见 "host_setup" 一节。



=== 使用 CLI 创建 LUN 并将 LUN 映射到启动程序组

本节展示了使用 ONTAP 9 命令行为 SAP HANA 单主机系统（SID FC5，使用 LVM 且每个 LVM 卷组有两个 LUN）配置的示例配置：

. 创建所有 LUN 。
+
....
lun create -path  FC5_data_mnt00001   -size 1t -ostype linux  -class regular
lun create -path FC5_data2_mnt00001 -size 1t -ostype linux  -class regular
lun create -path FC5_log_mnt00001 -size 260g -ostype linux  -class regular
lun create -path FC5_log2_mnt00001 -size 260g -ostype linux  -class regular
lun create -path FC5_shared -size 260g -ostype linux  -class regular

....
. 为属于系统 FC5 的所有服务器创建启动程序组。
+
....
lun igroup create -igroup HANA-FC5 -protocol fcp -ostype linux -initiator 10000090fadcc5fa,10000090fadcc5fb -vserver svm1
....
. 将所有 LUN 映射到已创建的启动程序组。
+
....
lun map -path FC5_data_mnt00001    -igroup HANA-FC5
lun map -path FC5_data2_mnt00001  -igroup HANA-FC5
lun map -path FC5_log_mnt00001  -igroup HANA-FC5
lun map -path FC5_log2_mnt00001  -igroup HANA-FC5
lun map -path FC5_shared  -igroup HANA-FC5
....

