---
sidebar: sidebar 
permalink: bp/hana-asa-fc-host-setup_single.html 
keywords: multipathing, fcp, hba, configure 
summary: 在设置主机之前，必须从 NetApp 支持站点下载 NetApp SAN 主机实用程序，并将其安装在 HANA 服务器上。主机实用程序文档提供了有关根据所使用的 FCP HBA 而必须安装的其他软件的信息。 
---
= 单主机设置
:allow-uri-read: 




== 单主机设置

[role="lead"]
本章介绍 SAP HANA 单主机的设置。



== SAP HANA 单主机系统的 LUN 配置

Linux LVM 用于提高性能并解决 LUN 大小限制。在 SAP HANA 主机上，需要创建和挂载卷组和逻辑卷，如下表所示。

|===
| 逻辑卷 /LUN | SAP HANA 主机上的挂载点 | 注意 


| LV：FC5_data_mnt00001-vol | /ha/data/FC5/mnt00001 | 已使用 /etc/fstab 条目挂载 


| LV：FC5_log_mnt00001-vol | /ha/log/FC5/mnt00001 | 已使用 /etc/fstab 条目挂载 


| LUN：FC5_共享 | /has/shared/FC5 | 已使用 /etc/fstab 条目挂载 
|===

NOTE: 通过所述配置，  `/usr/sap/FC5`存储用户 FC5adm 默认主目录的目录位于本地磁盘上。在基于磁盘的复制灾难恢复设置中，NetApp 建议为 `/usr/sap/FC5`目录，以便所有文件系统都位于中央存储上。



=== 创建 LVM 卷组和逻辑卷

. 将所有 LUN 初始化为物理卷。
+
....
pvcreate /dev/mapper/svm1-FC5_data_mnt00001_1
pvcreate /dev/mapper/svm1-FC5_data_mnt00001_2
pvcreate /dev/mapper/svm1-FC5_log_mnt00001_1
pvcreate /dev/mapper/svm1-FC5_log_mnt00001_2
....
. 为每个数据和日志分区创建卷组。
+
....
vgcreate FC5_data_mnt00001 /dev/mapper/svm1-FC5_data_mnt00001_1 /dev/mapper/svm1-FC5_data_mnt00001_2
vgcreate FC5_log_mnt00001 /dev/mapper/svm1-FC5_log_mnt00001_1 /dev/mapper/svm1-FC5_log_mnt00001_2
....
. 为每个数据和日志分区创建一个逻辑卷。使用的条带大小等于每个卷组使用的 LUN 数量（在此示例中为 2 个），数据条带大小为 256k ，日志条带大小为 64k 。SAP 仅支持每个卷组一个逻辑卷。
+
....
lvcreate --extents 100%FREE -i 2 -I 256k --name vol FC5_data_mnt00001
lvcreate --extents 100%FREE -i 2 -I 64k --name vol FC5_log_mnt00001
....
. 扫描所有其他主机上的物理卷，卷组和卷组。


....
modprobe dm_mod
pvscan
vgscan
lvscan
....

NOTE: 如果这些命令未找到卷，则需要重新启动。

要挂载逻辑卷，必须激活逻辑卷。要激活卷，请运行以下命令：

....
vgchange -a y
....


=== 创建文件系统

在所有数据和日志逻辑卷以及 hana 共享 LUN 上创建 XFS 文件系统。

....
mkfs.xfs /dev/mapper/FC5_data_mnt00001-vol
mkfs.xfs /dev/mapper/FC5_log_mnt00001-vol
mkfs.xfs /dev/mapper/svm1-FC5_shared
....

NOTE: 多主机示例命令显示 2+1 多主机 HANA 系统。



=== 创建挂载点

创建所需的挂载点目录，并在数据库主机上设置权限：

....
sapcc-hana-tst:/ # mkdir -p /hana/data/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/log/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/shared
sapcc-hana-tst:/ # chmod -R 777 /hana/log/FC5
sapcc-hana-tst:/ # chmod -R 777 /hana/data/FC5
sapcc-hana-tst:/ # chmod 777 /hana/shared
....


=== 挂载文件系统

使用以下方式在系统启动期间挂载文件系统 `/etc/fstab`配置文件，将所需的文件系统添加到 `/etc/fstab`配置文件：

....
# cat /etc/fstab
/dev/mapper/hana-FC5_shared /hana/shared xfs defaults 0 0
/dev/mapper/FC5_log_mnt00001-vol /hana/log/FC5/mnt00001 xfs relatime,inode64 0 0
/dev/mapper/FC5_data_mnt00001-vol /hana/data/FC5/mnt00001 xfs relatime,inode64 0 0
....

NOTE: 必须使用 `relatime` 和 `inode64` 挂载选项挂载数据和日志 LUN 的 XFS 文件系统。

要挂载文件系统，请运行以下命令： `mount -a` 在主机上执行命令。
