---
sidebar: sidebar 
permalink: bp/hana-asa-fc-storage-controller-setup_multiple_hosts.html 
keywords: storage efficiency, netapp volume encryption, quality of service, qos, fabricpool, Disk shelf, sas, fcp port sets, linux lvm, 
summary: 本节介绍如何为多主机系统创建 LUN 
---
= 存储控制器设置 - 多台主机
:allow-uri-read: 




== 存储控制器设置 - 多台主机

[role="lead"]
本节介绍针对 SAP HANA 多主机系统的 NetApp 存储系统配置



== SAP HANA 多主机系统的 LUN 配置

Linux LVM 用于提高性能并解决 LUN 大小限制。

在 SAP HANA 主机上，需要创建和挂载卷组和逻辑卷，如下表所示。

|===
| 逻辑卷 (LV) | SAP HANA 主机上的挂载点 | 注意 


| LV：FC5_data_mnt00001-vol | /ha/data/FC5/mnt00001 | 使用存储连接器挂载 


| LV：FC5_log_mnt00001-vol | /ha/log/FC5/mnt00001 | 使用存储连接器挂载 


| LV：FC5_data_mnt00002-vol | /ha/data/FC5/mnt00002 | 使用存储连接器挂载 


| LV：FC5_log_mnt00002-vol | /ha/log/FC5/mnt00002 | 使用存储连接器挂载 


| 外部 NFS 共享：FC5_shared | /has/ 共享 | 使用 NFS 和 /etc/fstab 条目挂载在所有主机上 
|===

NOTE: SAP HANA 多主机系统需要 `/hana/shared`连接到系统所有主机的文件系统。通常，这是由 NFS 服务器提供的 NFS 共享。建议使用高可用性 NFS 服务器，例如 NetApp FAS 或 AFF 系统。另一种选择是使用 LINUX 主机的内置 NFS 服务器。


NOTE: 通过所述配置，  `/usr/sap/FC5`存储用户 FC5adm 默认主目录的目录位于每个 HANA 主机的本地磁盘上。在基于磁盘的复制灾难恢复设置中，NetApp 建议使用四个额外的 LUN 用于 `/usr/sap/FC5`文件系统，以便每个数据库主机在中央存储上都有其所有的文件系统。



== 创建 LUN 并将 LUN 映射到启动程序组

您可以使用NetApp ONTAP系统管理器创建存储卷和LUN、并将其映射到服务器的igrou和ONTAP命令行界面。本指南介绍命令行界面的用法。


NOTE: `sanlun` 工具是 NetApp Host Utilities 的一部分，必须安装在每个 SAP HANA 主机上。有关详细信息，请参见 "host_setup" 一节。



=== 使用 CLI 创建 LUN 并将 LUN 映射到启动程序组

本节展示了使用 ONTAP 9 命令行为 2+1 SAP HANA 多主机系统配置示例，该系统采用 FC5 FC5，使用 LVM，每个 LVM 卷组有两个 LUN：

. 创建所有 LUN 。
+
....
lun create -path FC5_data_mnt00001   -size 1t -ostype linux  -class regular
lun create -path FC5_data2_mnt00001 -size 1t -ostype linux  -class regular
lun create -path FC5_data_mnt00002 -size 1t -ostype linux  -class regular
lun create -path FC5_data2_mnt00002 -size 1t -ostype linux  -class regular
lun create -path FC5_log_mnt00001 -size 260g -ostype linux  -class regular
lun create -path FC5_log2_mnt00001 -size 260g -ostype linux  -class regular
lun create -path FC5_log_mnt00002 -size 260g -ostype linux  -class regular
lun create -path FC5_log2_mnt00002 -size 260g -ostype linux  -class regular
....
. 为属于系统 FC5 的所有服务器创建启动程序组。
+
....
lun igroup create -igroup HANA-FC5 -protocol fcp -ostype linux -initiator 10000090fadcc5fa,10000090fadcc5fb,10000090fadcc5c1,10000090fadcc5c2,10000090fadcc5c3,10000090fadcc5c4 -vserver svm1
....
. 将所有 LUN 映射到已创建的启动程序组。
+
....
lun map -path FC5_data_mnt00001  -igroup HANA-FC5
lun map -path FC5_data2_mnt00001  -igroup HANA-FC5
lun map -path FC5_data_mnt00002  -igroup HANA-FC5
lun map -path FC5_data2_mnt00002  -igroup HANA-FC5
lun map -path FC5_log_mnt00001  -igroup HANA-FC5
lun map -path FC5_log2_mnt00001  -igroup HANA-FC5
lun map -path FC5_log_mnt00002  -igroup HANA-FC5
lun map -path FC5_log2_mnt00002  -igroup HANA-FC5
....

