---
sidebar: sidebar 
permalink: bp/saphana_aff_nfs_sap_hana_installation_preparations_for_nfsv4.html 
keywords:  
summary: NFS 版本 4 及更高版本需要用户身份验证。可以使用轻型目录访问协议（ Lightweight Directory Access Protocol ， LDAP ）服务器等中央用户管理工具或使用本地用户帐户来完成此身份验证。以下各节介绍如何配置本地用户帐户。 
---
= NFSv4 的 SAP HANA 安装准备
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NFS 版本 4 及更高版本需要用户身份验证。可以使用轻型目录访问协议（ Lightweight Directory Access Protocol ， LDAP ）服务器等中央用户管理工具或使用本地用户帐户来完成此身份验证。以下各节介绍如何配置本地用户帐户。

管理用户 `<sid>adm`,`<sid>crypt`开始安装SAP HANA软件之前、必须在SAP HANA主机和存储控制器上手动创建和 `sapsys`组。



== SAP HANA 主机

如果不存在，则必须在 SAP HANA 主机上创建 `sapsys` 组。必须选择一个不与存储控制器上的现有组 ID 冲突的唯一组 ID 。

用户 `<sid>adm`和 `<sid>crypt`将在SAP HANA主机上创建。必须选择不与存储控制器上的现有用户ID冲突的唯一ID。

对于多主机SAP HANA系统、所有SAP HANA主机上的用户ID和组ID必须相同。组和用户是通过将源系统中的受影响行复制到其他所有SAP HANA主机以及 `/etc/passwd`从源系统复制到其他所有SAP HANA主机来在其他SAP HANA主机上创建 `/etc/group`的。

对于多主机 SAP HANA 系统，所有 SAP HANA 主机上的用户和组 ID 必须相同。通过将 ` /etc/group` 和 ` /etc/passwd` 中的受影响行从源系统复制到所有其他 SAP HANA 主机，可以在其他 SAP HANA 主机上创建组和用户。


NOTE: 所有 Linux 服务器和 SVM 上的 NFSv4 域必须设置为相同的值。在文件 ` /etc/idmapd.conf` 中为 Linux 主机设置域参数 `Domain = <domain_name>` 。

启用并启动 NFS idmapd 服务：

....
systemctl enable nfs-idmapd.service
systemctl start nfs-idmapd.service
....

NOTE: 最新的 Linux 内核不需要执行此步骤。您可以安全地忽略警告消息。



== 存储控制器

SAP HANA 主机和存储控制器上的用户 ID 和组 ID 必须相同。可通过在存储集群上输入以下命令来创建组和用户：

....
vserver services unix-group create -vserver <vserver> -name <group name> -id <group id>
vserver services unix-user create -vserver <vserver> -user <user name> -id <user-id> -primary-gid <group id>
....
此外，将 SVM 的 UNIX 用户 root 的组 ID 设置为 0 。

....
vserver services unix-user modify -vserver <vserver> -user root -primary-gid 0
....